

vault_version: "1.15.6"

vault_user: vault
vault_group: vault

vault_port: 8200
vault_cluster_port: 8201

vault_config_dir: /etc/vault.d
vault_data_dir: /opt/vault/data

vault_ui: true

vault_listener_address: "0.0.0.0:8200"